name: Build and Export Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t aq-music:latest .
          docker save aq-music:latest -o aq-music.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aq-music-docker-image
          path: aq-music.tar
          retention-days: 7
